import React from "react";
import ProductList from "@/components/ProductList/ProductList";
import Women1 from "@/Public/Assets/Images/Products/Women/Smart-1.jpeg";
import Women2 from "@/Public/Assets/Images/Products/Women/Smart-2.jpeg";
import Women3 from "@/Public/Assets/Images/Products/Women/Smart-3.jpeg";
import Women4 from "@/Public/Assets/Images/Products/Women/Street-1.jpeg";
import Women5 from "@/Public/Assets/Images/Products/Women/Street-2.jpeg";
import Women6 from "@/Public/Assets/Images/Products/Women/Bride-1.jpeg";
import Women7 from "@/Public/Assets/Images/Products/Women/Bride-3.jpg";
import Women8 from "@/Public/Assets/Images/Products/Women/Festive-1.jpg";
import Women9 from "@/Public/Assets/Images/Products/Women/Indo-west1.jpeg";
import Women10 from "@/Public/Assets/Images/Products/Women/Indo-west2.jpeg";

const WomenProductData = [
  {
    id: 1,
    name: "Elegant Evening Dress",
    image: Women1,
    price: 180,
    discountPrice: 150,
    description: "Stunning evening dress perfect for formal occasions",
    rating: 4.7,
    reviews: 120,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 2,
    name: "Business Casual Blazer",
    image: Women2,
    price: 140,
    discountPrice: 120,
    description: "Professional blazer for office wear",
    rating: 4.5,
    reviews: 85,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 3,
    name: "Summer Floral Dress",
    image: Women3,
    price: 90,
    discountPrice: 75,
    description: "Light and breezy floral dress for summer",
    rating: 4.3,
    reviews: 95,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 4,
    name: "Urban Street Jacket",
    image: Women9,
    price: 120,
    discountPrice: 100,
    description: "Trendy street-style denim jacket",
    rating: 4.6,
    reviews: 78,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 5,
    name: "Casual Weekend Set",
    image: Women5,
    price: 85,
    discountPrice: 70,
    description: "Comfortable weekend wear set",
    rating: 4.4,
    reviews: 110,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 6,
    name: "Bridal Collection Gown",
    image: Women6,
    price: 500,
    discountPrice: 450,
    description: "Exquisite bridal gown with detailed embroidery",
    rating: 4.9,
    reviews: 45,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    isSale: false,
    isStock: true,
    link: "/",
  },
  {
    id: 7,
    name: "Wedding Reception Dress",
    image: Women7,
    price: 300,
    discountPrice: 260,
    description: "Elegant reception dress with modern design",
    rating: 4.7,
    reviews: 65,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 8,
    name: "Festival Collection Saree",
    image: Women8,
    price: 200,
    discountPrice: 175,
    description: "Traditional festive wear saree",
    rating: 4.8,
    reviews: 92,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 9,
    name: "Indo-Western Fusion Dress",
    image: Women4,
    price: 150,
    discountPrice: 130,
    description: "Modern fusion of traditional and western styles",
    rating: 4.5,
    reviews: 88,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 10,
    name: "Contemporary Ethnic Wear",
    image: Women10,
    price: 180,
    discountPrice: 155,
    description: "Contemporary take on traditional ethnic wear",
    rating: 4.6,
    reviews: 75,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
];

function Women() {
  return <ProductList ProductData={WomenProductData} />;
}

export default Women;
