import React from "react";
import Men1 from "@/Public/Assets/Images/Products/Men/Men-2.jpeg";
import Men2 from "@/Public/Assets/Images/Products/Men/Gentelman-1.jpeg";
import Men3 from "@/Public/Assets/Images/Products/Men/Men-Trad1.jpg";
import Men4 from "@/Public/Assets/Images/Products/Men/Gentelman-3.jpeg";
import Men5 from "@/Public/Assets/Images/Products/Men/Kurta-3.jpg";
import Men6 from "@/Public/Assets/Images/Products/Men/Kurta-5.jpg";
import Men7 from "@/Public/Assets/Images/Products/Men/Punjabi-1.jpeg";
import Men8 from "@/Public/Assets/Images/Products/Men/Street-1.jpg";
import Men9 from "@/Public/Assets/Images/Products/Men/Street-2.jpg";
import Men10 from "@/Public/Assets/Images/Products/Men/Groom-6.jpg";
import ProductList from "@/components/ProductList/ProductList";

const MenProductData = [
  {
    id: 1,
    name: "Nike Cotton T-Shirt",
    image: Men1,
    price: 100,
    discountPrice: 90,
    description: "Classic cotton t-shirt with Nike branding",
    rating: 4.5,
    reviews: 100,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 2,
    name: "Adidas Running Shoes",
    image: Men2,
    price: 150,
    discountPrice: 130,
    description: "Lightweight running shoes with superior comfort",
    rating: 4.8,
    reviews: 250,
    isNew: false,
    isBestSeller: true,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 3,
    name: "Puma Sports Track Pants",
    image: Men3,
    price: 80,
    discountPrice: 65,
    description: "Comfortable track pants for active lifestyle",
    rating: 4.3,
    reviews: 75,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 4,
    name: "Under Armour Gym Bag",
    image: Men4,
    price: 60,
    discountPrice: 45,
    description: "Spacious gym bag with multiple compartments",
    rating: 4.6,
    reviews: 120,
    isNew: false,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 5,
    name: "Reebok Fitness Watch",
    image: Men5,
    price: 200,
    discountPrice: 180,
    description: "Smart fitness tracker with heart rate monitor",
    rating: 4.7,
    reviews: 180,
    isNew: true,
    isBestSeller: true,
    isFeatured: false,
    isSale: false,
    isStock: true,
    link: "/",
  },
  {
    id: 6,
    name: "New Balance Walking Shoes",
    image: Men6,
    price: 120,
    discountPrice: 100,
    description: "Comfortable walking shoes for daily use",
    rating: 4.4,
    reviews: 90,
    isNew: false,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 7,
    name: "Nike Sports Socks Pack",
    image: Men7,
    price: 25,
    discountPrice: 20,
    description: "Pack of 3 moisture-wicking sports socks",
    rating: 4.2,
    reviews: 150,
    isNew: false,
    isBestSeller: true,
    isFeatured: false,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 8,
    name: "Adidas Training Shorts",
    image: Men8,
    price: 45,
    discountPrice: 35,
    description: "Breathable training shorts with pockets",
    rating: 4.5,
    reviews: 85,
    isNew: true,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 9,
    name: "Puma Sports Water Bottle",
    image: Men9,
    price: 30,
    discountPrice: 25,
    description: "1L sports water bottle with easy grip",
    rating: 4.1,
    reviews: 60,
    isNew: false,
    isBestSeller: false,
    isFeatured: true,
    isSale: true,
    isStock: true,
    link: "/",
  },
  {
    id: 10,
    name: "Under Armour Compression Shirt",
    image: Men10,
    price: 70,
    discountPrice: 60,
    description: "Long sleeve compression shirt for training",
    rating: 4.6,
    reviews: 110,
    isNew: true,
    isBestSeller: true,
    isFeatured: true,
    isSale: false,
    isStock: true,
    link: "/",
  },
];

function Men() {
  return (
    <div>
      <ProductList ProductData={MenProductData} />
    </div>
  );
}

export default Men;
